version: '3'
services:
  django:
    build:
      context: expense_tracker
      dockerfile: Dockerfile
    image: expense_tracker_django
    container_name: expense-tracker-django
    restart: unless-stopped
    env_file: expense_tracker/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8000:8000
    volumes:
      - ./expense_tracker:/app
    networks:
      - app-network
    command:
      - /bin/sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: